[package]
name = "fusion-generator-core"
version = "0.1.0"
edition = "2018"

[dependencies]
concat-string = "^1.0.1"
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter.git", tag = "v0.20.0" }
